"""add_test_status_license_modules

Revision ID: 2923d36c72e5
Revises: 2dec74efbc16
Create Date: 2026-03-18 08:29:18.788946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2923d36c72e5'
down_revision: Union[str, None] = '2dec74efbc16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hmr_sessions_crew_profile_id', table_name='hmr_sessions')
    op.drop_index('ix_hmr_sessions_id', table_name='hmr_sessions')
    op.drop_table('hmr_sessions')
    op.add_column('questions', sa.Column('module_index', sa.Integer(), nullable=True))
    op.add_column('test_catalogues', sa.Column('status', sa.String(), nullable=False, server_default='ALPHA'))
    op.add_column('test_catalogues', sa.Column('license', sa.String(), nullable=False, server_default='CUSTOM_ALPHA'))
    op.add_column('test_catalogues', sa.Column('validation_notes', sa.Text(), nullable=True))
    op.add_column('test_catalogues', sa.Column('modules_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_catalogues', 'modules_config')
    op.drop_column('test_catalogues', 'validation_notes')
    op.drop_column('test_catalogues', 'license')
    op.drop_column('test_catalogues', 'status')
    op.drop_column('questions', 'module_index')
    op.create_table('hmr_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('crew_profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('theta_estimate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('se_estimate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('responses_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('items_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('final_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crew_profile_id'], ['crew_profiles.id'], name='hmr_sessions_crew_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='hmr_sessions_pkey')
    )
    op.create_index('ix_hmr_sessions_id', 'hmr_sessions', ['id'], unique=False)
    op.create_index('ix_hmr_sessions_crew_profile_id', 'hmr_sessions', ['crew_profile_id'], unique=False)
    # ### end Alembic commands ###
