"""add_hmr_sessions_table

Revision ID: 2dec74efbc16
Revises: a3c87277bce1
Create Date: 2026-03-06 15:37:44.873953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dec74efbc16'
down_revision: Union[str, None] = 'a3c87277bce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hmr_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crew_profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('theta_estimate', sa.Float(), nullable=True),
    sa.Column('se_estimate', sa.Float(), nullable=True),
    sa.Column('responses_json', sa.JSON(), nullable=False),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['crew_profile_id'], ['crew_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hmr_sessions_crew_profile_id'), 'hmr_sessions', ['crew_profile_id'], unique=False)
    op.create_index(op.f('ix_hmr_sessions_id'), 'hmr_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hmr_sessions_id'), table_name='hmr_sessions')
    op.drop_index(op.f('ix_hmr_sessions_crew_profile_id'), table_name='hmr_sessions')
    op.drop_table('hmr_sessions')
    # ### end Alembic commands ###
