"""refactor_assessment_models

Revision ID: a3c87277bce1
Revises: b84537ba4c56
Create Date: 2026-02-23 13:58:44.548236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c87277bce1'
down_revision: Union[str, None] = 'b84537ba4c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_catalogues', sa.Column('name', sa.String(), nullable=False))
    op.add_column('test_catalogues', sa.Column('description', sa.String(), nullable=True))
    op.add_column('test_catalogues', sa.Column('n_questions', sa.Integer(), nullable=True))
    op.drop_column('test_catalogues', 'nom_du_test')
    op.drop_column('test_catalogues', 'description_courte')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_catalogues', sa.Column('description_courte', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('test_catalogues', sa.Column('nom_du_test', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('test_catalogues', 'n_questions')
    op.drop_column('test_catalogues', 'description')
    op.drop_column('test_catalogues', 'name')
    # ### end Alembic commands ###
