"""add survey title

Revision ID: b84537ba4c56
Revises: 001_initial
Create Date: 2026-02-23 13:40:43.228259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b84537ba4c56'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_campaign_candidates_campaign_id'), 'campaign_candidates', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_candidates_crew_profile_id'), 'campaign_candidates', ['crew_profile_id'], unique=False)
    op.create_index(op.f('ix_campaign_candidates_id'), 'campaign_candidates', ['id'], unique=False)
    op.drop_constraint('campaign_candidates_campaign_id_fkey', 'campaign_candidates', type_='foreignkey')
    op.drop_constraint('campaign_candidates_crew_profile_id_fkey', 'campaign_candidates', type_='foreignkey')
    op.create_foreign_key(None, 'campaign_candidates', 'campaigns', ['campaign_id'], ['id'])
    op.create_foreign_key(None, 'campaign_candidates', 'crew_profiles', ['crew_profile_id'], ['id'])
    op.alter_column('campaigns', 'position',
               existing_type=postgresql.ENUM('Captain', 'First Mate', 'Bosun', 'Deckhand', 'Chief Engineer', '2nd Engineer', 'Chief Stewardess', 'Stewardess', 'Chef', name='yachtposition'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('campaigns', 'status',
               existing_type=postgresql.ENUM('open', 'closed', 'draft', name='campaignstatus'),
               nullable=False,
               existing_server_default=sa.text("'open'::campaignstatus"))
    op.create_index(op.f('ix_campaigns_employer_profile_id'), 'campaigns', ['employer_profile_id'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_yacht_id'), 'campaigns', ['yacht_id'], unique=False)
    op.drop_constraint('campaigns_yacht_id_fkey', 'campaigns', type_='foreignkey')
    op.drop_constraint('campaigns_employer_profile_id_fkey', 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'employer_profiles', ['employer_profile_id'], ['id'])
    op.create_foreign_key(None, 'campaigns', 'yachts', ['yacht_id'], ['id'])
    op.create_index(op.f('ix_crew_assignments_crew_profile_id'), 'crew_assignments', ['crew_profile_id'], unique=False)
    op.create_index(op.f('ix_crew_assignments_id'), 'crew_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_crew_assignments_yacht_id'), 'crew_assignments', ['yacht_id'], unique=False)
    op.drop_constraint('crew_assignments_yacht_id_fkey', 'crew_assignments', type_='foreignkey')
    op.drop_constraint('crew_assignments_crew_profile_id_fkey', 'crew_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'crew_assignments', 'yachts', ['yacht_id'], ['id'])
    op.create_foreign_key(None, 'crew_assignments', 'crew_profiles', ['crew_profile_id'], ['id'])
    op.alter_column('crew_profiles', 'availability_status',
               existing_type=postgresql.ENUM('available', 'on_board', 'unavailable', 'soon', name='availabilitystatus'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'available'::availabilitystatus"))
    op.create_index(op.f('ix_crew_profiles_id'), 'crew_profiles', ['id'], unique=False)
    op.drop_constraint('crew_profiles_user_id_fkey', 'crew_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'crew_profiles', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_daily_pulses_crew_profile_id'), 'daily_pulses', ['crew_profile_id'], unique=False)
    op.create_index(op.f('ix_daily_pulses_id'), 'daily_pulses', ['id'], unique=False)
    op.create_index(op.f('ix_daily_pulses_yacht_id'), 'daily_pulses', ['yacht_id'], unique=False)
    op.drop_constraint('daily_pulses_crew_profile_id_fkey', 'daily_pulses', type_='foreignkey')
    op.drop_constraint('daily_pulses_yacht_id_fkey', 'daily_pulses', type_='foreignkey')
    op.create_foreign_key(None, 'daily_pulses', 'crew_profiles', ['crew_profile_id'], ['id'])
    op.create_foreign_key(None, 'daily_pulses', 'yachts', ['yacht_id'], ['id'])
    op.create_index(op.f('ix_employer_profiles_id'), 'employer_profiles', ['id'], unique=False)
    op.drop_constraint('employer_profiles_user_id_fkey', 'employer_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'employer_profiles', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_test_id'), 'questions', ['test_id'], unique=False)
    op.drop_constraint('questions_test_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'test_catalogues', ['test_id'], ['id'])
    op.alter_column('recruitment_events', 'outcome',
               existing_type=postgresql.ENUM('pending', 'hired', 'rejected', 'joined', name='applicationstatus'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'hired'::applicationstatus"))
    op.alter_column('recruitment_events', 'departure_reason',
               existing_type=postgresql.ENUM('performance', 'team_conflict', 'environment', 'leadership', 'external', 'unknown', name='departurereason'),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_recruitment_events_crew_profile_id'), 'recruitment_events', ['crew_profile_id'], unique=False)
    op.create_index(op.f('ix_recruitment_events_id'), 'recruitment_events', ['id'], unique=False)
    op.create_index(op.f('ix_recruitment_events_yacht_id'), 'recruitment_events', ['yacht_id'], unique=False)
    op.drop_constraint('recruitment_events_campaign_id_fkey', 'recruitment_events', type_='foreignkey')
    op.drop_constraint('recruitment_events_yacht_id_fkey', 'recruitment_events', type_='foreignkey')
    op.create_foreign_key(None, 'recruitment_events', 'yachts', ['yacht_id'], ['id'])
    op.create_foreign_key(None, 'recruitment_events', 'campaigns', ['campaign_id'], ['id'])
    op.alter_column('survey_responses', 'trigger_type',
               existing_type=postgresql.ENUM('post_charter', 'post_season', 'monthly_pulse', 'conflict_event', 'exit_interview', name='surveytriggertype'),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_survey_responses_crew_profile_id'), 'survey_responses', ['crew_profile_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_id'), 'survey_responses', ['id'], unique=False)
    op.create_index(op.f('ix_survey_responses_survey_id'), 'survey_responses', ['survey_id'], unique=False)
    op.drop_constraint('survey_responses_survey_id_fkey', 'survey_responses', type_='foreignkey')
    op.create_foreign_key(None, 'survey_responses', 'surveys', ['survey_id'], ['id'])
    op.add_column('surveys', sa.Column('title', sa.String(), nullable=True))
    op.alter_column('surveys', 'trigger_type',
               existing_type=postgresql.ENUM('post_charter', 'post_season', 'monthly_pulse', 'conflict_event', 'exit_interview', name='surveytriggertype'),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_surveys_id'), 'surveys', ['id'], unique=False)
    op.create_index(op.f('ix_surveys_yacht_id'), 'surveys', ['yacht_id'], unique=False)
    op.drop_constraint('surveys_yacht_id_fkey', 'surveys', type_='foreignkey')
    op.create_foreign_key(None, 'surveys', 'yachts', ['yacht_id'], ['id'])
    op.create_index(op.f('ix_test_catalogues_id'), 'test_catalogues', ['id'], unique=False)
    op.create_index(op.f('ix_test_results_crew_profile_id'), 'test_results', ['crew_profile_id'], unique=False)
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    op.create_index(op.f('ix_test_results_test_id'), 'test_results', ['test_id'], unique=False)
    op.drop_constraint('test_results_crew_profile_id_fkey', 'test_results', type_='foreignkey')
    op.create_foreign_key(None, 'test_results', 'crew_profiles', ['crew_profile_id'], ['id'])
    op.create_index(op.f('ix_user_documents_id'), 'user_documents', ['id'], unique=False)
    op.create_index(op.f('ix_user_documents_user_id'), 'user_documents', ['user_id'], unique=False)
    op.drop_constraint('user_documents_user_id_fkey', 'user_documents', type_='foreignkey')
    op.create_foreign_key(None, 'user_documents', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_harmony_verified'), 'users', ['is_harmony_verified'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_yachts_employer_profile_id'), 'yachts', ['employer_profile_id'], unique=False)
    op.create_index(op.f('ix_yachts_id'), 'yachts', ['id'], unique=False)
    op.drop_constraint('yachts_employer_profile_id_fkey', 'yachts', type_='foreignkey')
    op.create_foreign_key(None, 'yachts', 'employer_profiles', ['employer_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yachts', type_='foreignkey')
    op.create_foreign_key('yachts_employer_profile_id_fkey', 'yachts', 'employer_profiles', ['employer_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_yachts_id'), table_name='yachts')
    op.drop_index(op.f('ix_yachts_employer_profile_id'), table_name='yachts')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_harmony_verified'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'user_documents', type_='foreignkey')
    op.create_foreign_key('user_documents_user_id_fkey', 'user_documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_documents_user_id'), table_name='user_documents')
    op.drop_index(op.f('ix_user_documents_id'), table_name='user_documents')
    op.drop_constraint(None, 'test_results', type_='foreignkey')
    op.create_foreign_key('test_results_crew_profile_id_fkey', 'test_results', 'crew_profiles', ['crew_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_test_results_test_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_crew_profile_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_catalogues_id'), table_name='test_catalogues')
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.create_foreign_key('surveys_yacht_id_fkey', 'surveys', 'yachts', ['yacht_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_surveys_yacht_id'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_id'), table_name='surveys')
    op.alter_column('surveys', 'trigger_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('post_charter', 'post_season', 'monthly_pulse', 'conflict_event', 'exit_interview', name='surveytriggertype'),
               existing_nullable=False)
    op.drop_column('surveys', 'title')
    op.drop_constraint(None, 'survey_responses', type_='foreignkey')
    op.create_foreign_key('survey_responses_survey_id_fkey', 'survey_responses', 'surveys', ['survey_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_survey_responses_survey_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_crew_profile_id'), table_name='survey_responses')
    op.alter_column('survey_responses', 'trigger_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('post_charter', 'post_season', 'monthly_pulse', 'conflict_event', 'exit_interview', name='surveytriggertype'),
               existing_nullable=False)
    op.drop_constraint(None, 'recruitment_events', type_='foreignkey')
    op.drop_constraint(None, 'recruitment_events', type_='foreignkey')
    op.create_foreign_key('recruitment_events_yacht_id_fkey', 'recruitment_events', 'yachts', ['yacht_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('recruitment_events_campaign_id_fkey', 'recruitment_events', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_recruitment_events_yacht_id'), table_name='recruitment_events')
    op.drop_index(op.f('ix_recruitment_events_id'), table_name='recruitment_events')
    op.drop_index(op.f('ix_recruitment_events_crew_profile_id'), table_name='recruitment_events')
    op.alter_column('recruitment_events', 'departure_reason',
               existing_type=sa.String(),
               type_=postgresql.ENUM('performance', 'team_conflict', 'environment', 'leadership', 'external', 'unknown', name='departurereason'),
               existing_nullable=True)
    op.alter_column('recruitment_events', 'outcome',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'hired', 'rejected', 'joined', name='applicationstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'hired'::applicationstatus"))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_test_id_fkey', 'questions', 'test_catalogues', ['test_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_questions_test_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.drop_constraint(None, 'employer_profiles', type_='foreignkey')
    op.create_foreign_key('employer_profiles_user_id_fkey', 'employer_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_employer_profiles_id'), table_name='employer_profiles')
    op.drop_constraint(None, 'daily_pulses', type_='foreignkey')
    op.drop_constraint(None, 'daily_pulses', type_='foreignkey')
    op.create_foreign_key('daily_pulses_yacht_id_fkey', 'daily_pulses', 'yachts', ['yacht_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('daily_pulses_crew_profile_id_fkey', 'daily_pulses', 'crew_profiles', ['crew_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_daily_pulses_yacht_id'), table_name='daily_pulses')
    op.drop_index(op.f('ix_daily_pulses_id'), table_name='daily_pulses')
    op.drop_index(op.f('ix_daily_pulses_crew_profile_id'), table_name='daily_pulses')
    op.drop_constraint(None, 'crew_profiles', type_='foreignkey')
    op.create_foreign_key('crew_profiles_user_id_fkey', 'crew_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_crew_profiles_id'), table_name='crew_profiles')
    op.alter_column('crew_profiles', 'availability_status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('available', 'on_board', 'unavailable', 'soon', name='availabilitystatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'available'::availabilitystatus"))
    op.drop_constraint(None, 'crew_assignments', type_='foreignkey')
    op.drop_constraint(None, 'crew_assignments', type_='foreignkey')
    op.create_foreign_key('crew_assignments_crew_profile_id_fkey', 'crew_assignments', 'crew_profiles', ['crew_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('crew_assignments_yacht_id_fkey', 'crew_assignments', 'yachts', ['yacht_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_crew_assignments_yacht_id'), table_name='crew_assignments')
    op.drop_index(op.f('ix_crew_assignments_id'), table_name='crew_assignments')
    op.drop_index(op.f('ix_crew_assignments_crew_profile_id'), table_name='crew_assignments')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key('campaigns_employer_profile_id_fkey', 'campaigns', 'employer_profiles', ['employer_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('campaigns_yacht_id_fkey', 'campaigns', 'yachts', ['yacht_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_campaigns_yacht_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_employer_profile_id'), table_name='campaigns')
    op.alter_column('campaigns', 'status',
               existing_type=postgresql.ENUM('open', 'closed', 'draft', name='campaignstatus'),
               nullable=True,
               existing_server_default=sa.text("'open'::campaignstatus"))
    op.alter_column('campaigns', 'position',
               existing_type=sa.String(),
               type_=postgresql.ENUM('Captain', 'First Mate', 'Bosun', 'Deckhand', 'Chief Engineer', '2nd Engineer', 'Chief Stewardess', 'Stewardess', 'Chef', name='yachtposition'),
               existing_nullable=False)
    op.drop_constraint(None, 'campaign_candidates', type_='foreignkey')
    op.drop_constraint(None, 'campaign_candidates', type_='foreignkey')
    op.create_foreign_key('campaign_candidates_crew_profile_id_fkey', 'campaign_candidates', 'crew_profiles', ['crew_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('campaign_candidates_campaign_id_fkey', 'campaign_candidates', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_campaign_candidates_id'), table_name='campaign_candidates')
    op.drop_index(op.f('ix_campaign_candidates_crew_profile_id'), table_name='campaign_candidates')
    op.drop_index(op.f('ix_campaign_candidates_campaign_id'), table_name='campaign_candidates')
    # ### end Alembic commands ###
